### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by dirtysouthgamingdev** [sethduda/AdvancedSlingLoading#6]
The following error gets written to the .rpt as soon as the server launches.

`15:54:31 File sa_advancedslingloading\config.cpp, line 34: '/CfgFunctions/SA/AdvancedSlingLoading/advancedSlingLoadingInit.postInit': Missing ';' prior '}'`

I've looked through `config.cpp` and `fn_advancedSlingLoadingInit.sqf`, but didn't see any obvious errors.

Worth mentioning this is being used on an Exile 0.9.8 server.

**Comment by sethduda** [comment]
This has been fixed by #8
