### ISSUE TITLE
Vehicle doesn't support cargo ropes

### ISSUE THREAD

**Issue by thegoatman** [sethduda/AdvancedSlingLoading#7]
The message "Vehicle doesn't support cargo ropes" comes up randomly even if the vehicle was able to use cargo ropes before

**Comment by sethduda** [comment]
Do you see the problem only when the vehicle is on the ground? or does it happen in the air as well?

**Comment by thegoatman** [comment]
Checking now reporting back in 2 mins

**Comment by thegoatman** [comment]
Yes when in the air it works. After landing it keeps working like it did before trowing the error.

**Comment by sethduda** [comment]
Ok, there's a line in the code:

_p0 = [0,0,0];

try changing it to 

_p0 = [0,0,0.1];

and see if that fixes it.

**Comment by thegoatman** [comment]
Alright adding it on the next restart

**Comment by thegoatman** [comment]
Seems to work so far thnx :)

**Comment by sethduda** [comment]
Great, I'll make the change to the source.
