### ISSUE TITLE
CUP Wildcat

### ISSUE THREAD

**Issue by thegoatman** [sethduda/AdvancedSlingLoading#9]
Deploying ropes on the CUP Wildcat destroy the rotors

**Comment by sethduda** [comment]
Ropes need to be moved down. Are you able to figure out the proper adjustments?

See ASL_SLING_LOAD_POINT_CLASS_HEIGHT_OFFSET 

the 3 values move the 3 sling load points x meters up/down from their original position. Defaults work for most vehicles. Some have problems though.

**Comment by thegoatman** [comment]
Am sure will be able to figure it out. Will report back with the correct values

**Comment by thegoatman** [comment]
Got it ["CUP_AW159_Unarmed_Base", [-0.05, -0.06, -0.05]] seems to fix the wildcats so far ;)

**Comment by sethduda** [comment]
Nice. You can make the change if you'd like

**Comment by thegoatman** [comment]
Done thnx for the awsome mod ;)
